### ISSUE TITLE
run.sh failed at Stage6

### ISSUE THREAD

**Issue by ysinha94** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#11]
Hi, while running run.sh stage 6 failed. steps/make_mfcc.sh: segments file does not exist.
How can I solve this issue?

![Screenshot 2022-03-31 15:42:14](https://user-images.githubusercontent.com/51052792/161069169-1e4120d4-1a5f-49eb-afa7-eb5f0437d609.png)

**Comment by ysinha94** [comment]
> 
Hi @Natalia-T, please see the attached log file. 
[make_mfcc_libritts_train_other_500.8.log](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/files/8396151/make_mfcc_libritts_train_other_500.8.log)

**Comment by Natalia-T** [comment]
Hi @ysinha94,
 According to your logs, the Kaldi commands (`compute-mfcc-feats`, `copy-feats`) were not found.
 Probably the Kaldi has not been installed.
 Please check your `env.sh` and see the following issue for details: 
https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/issues/12

**Comment by ysinha94** [comment]
Thank you this worked.
