### ISSUE TITLE
VCTK Dev text file is not normalized

### ISSUE THREAD

**Issue by yaoxunji** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#12]
I run all the steps in run.sh, but I found the WER of vctk dev datasets is 100%. It is due to the text file being lowercase and punctuation, I normalized the text, but the final WER of vctk dev datasets is still 1% higher than the result on GitHub. How can I deal with it?
my result
![1649743616(1)](https://user-images.githubusercontent.com/17915763/162891898-934584d2-f4b7-4e91-9656-f638a8b1dd38.png)
orig result
![1649743671(1)](https://user-images.githubusercontent.com/17915763/162892016-8f60f7c9-81f4-4b43-ab8d-54c8e130abc1.png)

**Comment by Voice-Privacy-Challenge** [comment]
Hi @yaoxunji,

The dev and test data preparation is performed at `Stage 0` of `run.sh` (`local/main_download_data.sh`).
See https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/master/baseline/local/download_data.sh#L29

Probably this stage was interrupted and the text normalization was not completed when you run the script.

Similar issue: https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/issues/3

**Comment by yaoxunji** [comment]
> Hi @yaoxunji,
> 
> The dev and test data preparation is performed at `Stage 0` of `run.sh` (`local/main_download_data.sh`). See https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/master/baseline/local/download_data.sh#L29
> 
> Probably this stage was interrupted and the text normalization was not completed when you run the script.
> 
> Similar issue: [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#3](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/issues/3)

Thank you for your response.
I have run the stage 0， and the WER of VCTK dev is **11.99**  rather than the **10.79** in original RESULT_summary_tts_pytorch file.

This is my result summary
[results_summary.txt](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/files/8481161/results_summary.txt)

**Comment by Natalia-T** [comment]
It looks like the normalization was performed differently in your experiments (i.e., for `ASR-vctk_dev_asr`, the total number of words (in the reference) in your test is 86625, and in the baseline - it is 86627).

Could you please attach for `ASR-vctk_dev_asr`:

- reference file  (file `.../baseline/exp/models/asr_eval/decode_vctk_dev_asr_tglarge/scoring_kaldi/test_filt.txt`)
- decoding results (file  `.../baseline/exp/models/asr_eval/decode_vctk_dev_asr_tglarge/scoring_kaldi/penalty_0.5/14.txt`)?

**Comment by yaoxunji** [comment]
Thank you, Natalia, for your response. This is a reference file and my decoding results
[14.txt](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/files/8489056/14.txt)
[test_filt.txt](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/files/8489062/test_filt.txt)

**Comment by Natalia-T** [comment]
Thank you @yaoxunji, one major difference in the reference files (test_filt.txt) is character `'`.
In your normalized file, this character is removed, while it is not removed in the original baseline scripts 
(see [test_filt___vctk_dev_asr.txt](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/files/8489210/test_filt___vctk_dev_asr.txt) ), i.e.
![image](https://user-images.githubusercontent.com/27712304/163393098-fe7802d8-39ad-4cba-a95b-4d6fdef19b9e.png)

**Comment by yaoxunji** [comment]
Thank you for your help, my issue has been solved@[Natalia-T](https://github.com/Natalia-T)
