### ISSUE TITLE
Issues with VoxCeleb

### ISSUE THREAD

**Issue by fra1993** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#13]
Hi, I have an issue with the download of the dataset: on the website listed in ./run.sh (stage 2) they mention the audios are temporary unavailable. Am I doing something wrong? Thanks.

**Comment by Natalia-T** [comment]
Hi @fra1993, the audio data files for VoxCeleb-1,2 should be downloaded by participants individually. The VoxCeleb team normally should send login/password for data download (upon request). 
I contacted the authors and asked them about the current problem with the audio data download.

**Comment by Natalia-T** [comment]
Hi @fra1993,
The data can be accessed from link provided by the VoxCeleb team: https://mm.kaist.ac.kr/voxceleb
