### ISSUE TITLE
Issue while running install.sh with cuda (11.1)

### ISSUE THREAD

**Issue by suhitaghosh10** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#15]
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/11187576/166488755-5a6fe6bb-05b2-41d6-a5e3-89781fa1fcfe.png">

The install finishes abruptly ,while performing make for "Kaldi". I surmise it is because of incompatibility between CUB and CUDA versions.

**Comment by Natalia-T** [comment]
Hi @suhitaghosh10,
I use CUDA Toolkit 11.3 and the installation works normally.
In the recipe, a fixed Kaldi version is used (6e03a3f, Nov 16, 2021, https://github.com/kaldi-asr/kaldi/commit/6e03a3f5f99d6d8c22494d90b7e7f9ceb0117ac8).
You can try to build the latest Kaldi version independently in your environment.

**Comment by suhitaghosh10** [comment]
It seems the issue is with CUDA 11.1
I tried with CUDA 11.2, it works. Thanks!
