### ISSUE TITLE
Out of disk space when running baseline b1.a

### ISSUE THREAD

**Issue by minhduc0711** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#16]
I ran `baseline/run.sh` with configs for B1.A and it stopped at stage 10 (anonymizing training data for retraining eval models) because the script used up my 761 GB hard drive.

What's the required disk space for running B1.A?

p/s: sorry if this is the wrong place to ask such questions.

**Comment by Natalia-T** [comment]
With all the downloaded corpora (including archives), it requires about 800 GB.

**Comment by minhduc0711** [comment]
Thank you, I will try again!

**Comment by minhduc0711** [comment]
Actually I was referring to the space requirement including the generation of xvectors as well. The baseline script has been staying in stage 10 for a few days, and this `baseline/exp` alone is taking ~1.3TB already.
![image](https://user-images.githubusercontent.com/34294427/167724843-effa3077-2399-49a9-8c06-fa4d327e430f.png)
Is this supposed to be normal? If yes, can you give me an estimate of how much space it will take when the baseline script finishes?
