### ISSUE TITLE
PLDA (LLR) scores compute

### ISSUE THREAD

**Issue by yaoxunji** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#28]
Is stage 20 used to calculate PLDA scores and the PLDA scores are in baseline/exp/result-*-*/$dset/scores?

**Comment by Natalia-T** [comment]
PLDA scores for ASV evaluation are generated at **[Stage 15](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/5a8c9f90af2fda729b573ceb1c1f690ed0ea1c1e/baseline/run.sh#L138)** (https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/master/baseline/local/main_eval_asv.sh).

**Stage 20** collects results for re-identification and the voice-distinctiveness preservation (secondary) metrics computed at **Stage 19** into results files.

> the PLDA scores are in baseline/exp/result--/$dset/scores?

Yes (to be more precise about `$dset`, it should be noted that the directory name also includes specification if the trial/enrollment data were anonymized or not; i.e.  `ASV-$dset_enrolls_anon-$dset_trials_f_anon`).

**Comment by yaoxunji** [comment]
Thank you for your reply!
